apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 15s
      queryTimeout: 60s
  
  - name: Loki
    type: loki
    access: proxy
    uid: P8E80F9AEF21F6940
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 5000
  
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
