@Web_HostAddress = https://localhost:5001/api/v1
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzQwMTkzNy1mYjdlLTQyZTctYjhiMC00NzI2MDM3YWJjZDAiLCJqdGkiOiI0ZTQ5NjNjOC1lNmIyLTQ2YjEtYmEzZC1jNzMxOGQ5YjAyNTYiLCJpYXQiOjE3NTY5Njk5NDEsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMmM0MDE5MzctZmI3ZS00MmU3LWI4YjAtNDcyNjAzN2FiY2QwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IndhcWFzX3NheWVkQGhvdG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoid2FxYXNfc2F5ZWRAaG90bWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlRlbmFudEFkbWluIiwibmJmIjoxNzU2OTY5OTQxLCJleHAiOjE3NTY5NzM1NDEsImlzcyI6IkNvbm5lY3RGbG93LkRldiIsImF1ZCI6IkNvbm5lY3RGbG93LkRldiJ9.rGoL6ISUUxe02ZJVH12VVcoQu96brUo4Qp3dNmUpAJI
@TenantId=10

# GET Get Current Subscription
GET {{Web_HostAddress}}/Subscriptions/GetSubscription
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

#POST Create Subscription
POST {{Web_HostAddress}}/Subscriptions/Create
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "planId": 2,
    "successUrl": "{{Web_HostAddress}}/success",
    "cancelUrl": "{{Web_HostAddress}}/cancel"
}

###

#GET Checkout Session
GET {{Web_HostAddress}}/Subscriptions/GetCheckoutSession/cs_test_b1r7vdYwnPpqGkH5FIl0WsDTpFX4admRuyQTQbj3bcU4iMecMY1ijCQsZ4
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

#PUT Update Subscription
PUT {{Web_HostAddress}}/Subscriptions/Update
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "newPlanId": 3
}

###

#POST Cancel Subscription
POST {{Web_HostAddress}}/Subscriptions/Cancel
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "cancelImmediately": false
}

###

#POST Reactivate Subscription
POST {{Web_HostAddress}}/Subscriptions/Reactivate
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
}

###

# GET Get Available Plans
GET {{Web_HostAddress}}/Subscriptions/GetAvailablePlans
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

#GET Calculate Refund Credit
GET {{Web_HostAddress}}/Subscriptions/CalculateRefundCredit
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###