@Web_HostAddress = https://localhost:5001/api/v1
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzc3OGU1Zi03MDAxLTQwNjYtODE0Zi1mMWM4ZDIwMWU4ZDkiLCJqdGkiOiIyNjFjYmE2Ni1mYmUwLTRmNWQtYjczOS1lY2E1NGY1NTYxMGQiLCJpYXQiOjE3NTcwMDk5MTIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTM3NzhlNWYtNzAwMS00MDY2LTgxNGYtZjFjOGQyMDFlOGQ5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IndhcWFzX3NheWVkQGhvdG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoid2FxYXNfc2F5ZWRAaG90bWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVGVuYW50QWRtaW4iLCJuYmYiOjE3NTcwMDk5MTIsImV4cCI6MTc1NzAxMzUxMiwiaXNzIjoiQ29ubmVjdEZsb3cuRGV2IiwiYXVkIjoiQ29ubmVjdEZsb3cuRGV2In0.FDpCG1FusOl2acNCcdEACD5IaXXh4_tNFDq3mLv1Pzg
@TenantId=2

# GET Get Current Subscription
GET {{Web_HostAddress}}/Subscriptions/GetSubscription
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

#POST Create Subscription
POST {{Web_HostAddress}}/Subscriptions/Create
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "planId": 2,
    "successUrl": "{{Web_HostAddress}}/success",
    "cancelUrl": "{{Web_HostAddress}}/cancel"
}

###

#PUT Update Subscription
PUT {{Web_HostAddress}}/Subscriptions/Update
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "newPlanId": 4
}

###

#POST Cancel Subscription
POST {{Web_HostAddress}}/Subscriptions/Cancel
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "cancelImmediately": false
}

###

#POST Reactivate Subscription
POST {{Web_HostAddress}}/Subscriptions/Reactivate
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
}

###

#POST Edit Billing Session
POST {{Web_HostAddress}}/Subscriptions/EditBilling
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

{
    "returnUrl": "{{Web_HostAddress}}/success"
}

###

#GET Checkout Session
GET {{Web_HostAddress}}/Subscriptions/GetCheckoutSession/cs_test_b1r7vdYwnPpqGkH5FIl0WsDTpFX4admRuyQTQbj3bcU4iMecMY1ijCQsZ4
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

# GET Get Available Plans
GET {{Web_HostAddress}}/Subscriptions/GetAvailablePlans
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###

#GET Calculate Refund Credit
GET {{Web_HostAddress}}/Subscriptions/CalculateRefundCredit
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
X-Tenant-ID: {{TenantId}}

###