# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001/api/v1

# Super Admin Credentials
# @Email=superadmin@connectflow.local
# @Password=SuperAdmin123!

# Tenant Admin Credentials
 @Email=tenantadmin@connectflow.local
 @Password=TenantAdmin123!

#@Email=waqas_sayed@hotmail.com
#@Password=SyedWaqas123!

@UserId=7a92ac09-81c1-46fa-812c-ae0085d5e920
@EmailConfirmationToken=CfDJ8I9Tjk8vOcdNsFAAFQwFrUC09UQc9s7iDvRB7khLIWbZEiIr7k/07JiE36LgWi9om04qKbQKtxdQ71U6j4Um4ufSYdrUPiBE3dCtBlvqI1DYxzf0QqivlCQlE2GMUZVLjPUU+tvRM6MBU0wv+JxzFpnI9D4LUJDcWrmFb8eW2OpYGs5JBYIwRW6+Rwddi4zRvg==
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMmZiNjQyNS04OWI4LTQ4YWYtYTg2ZC1iZjUxMzNlODk0MWMiLCJqdGkiOiJmZDIwY2ZjZS1kZGI4LTQzMzctODNhMy1kMjBjMmQ0ODM4NjIiLCJpYXQiOjE3NTU5NjE5NzYsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTJmYjY0MjUtODliOC00OGFmLWE4NmQtYmY1MTMzZTg5NDFjIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlbmFudGFkbWluQGNvbm5lY3RmbG93LmxvY2FsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidGVuYW50YWRtaW5AY29ubmVjdGZsb3cubG9jYWwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVGVuYW50QWRtaW4iLCJuYmYiOjE3NTU5NjE5NzYsImV4cCI6MTc1NTk2NTU3NiwiaXNzIjoiQ29ubmVjdEZsb3cuRGV2IiwiYXVkIjoiQ29ubmVjdEZsb3cuRGV2In0.6ExBrkSObSyZY6nGm0LTxuu4gdLom8hqoWf9VVyJyXQ
@RefreshToken=pok53btWBuJ+dQYRk/Zjdv76StYiv2Ldkxk9e9ZQUuIBJCjKZYim4LZ4qFLnjlkesENhWFVfC892XnEIVTbGSQ==
@PasswordToken=CfDJ8I9Tjk8vOcdNsFAAFQwFrUCeS4+V8JTHKQDL8qJUWGoHWjdnOaPPIcPBWfmO9Iaf26Dp37kHdmNGYtuB1Hy0ZaDza4vMQ+WJxVy5EYxa8LIDklvd9I1WWIo3rV94ZM8Fbhxf6T5FQuYlkvreL03IPRKs3J182HmdF+EtJUMTcx9wlfzCJ/KkV8XYkeD7jqx6wQ==

# POST Users Register
POST {{Web_HostAddress}}/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}",
  "firstName": "Syed",
  "lastName": "Waqas"
}

###

# POST Users Login
POST {{Web_HostAddress}}/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users ConfirmEmail
POST {{Web_HostAddress}}/Users/ConfirmEmail
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "confirmationToken": "{{EmailConfirmationToken}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/Users/Refresh
Content-Type: application/json

{
  "accessToken": "{{BearerToken}}",
  "refreshToken": "{{RefreshToken}}"
}

###

# POST Users ResetPassword
POST {{Web_HostAddress}}/Users/ResetPassword
Content-Type: application/json

{
  "email": "{{Email}}"
}

###

# POST Users UpdatePassword
POST {{Web_HostAddress}}/Users/UpdatePassword
content-Type: application/json

{
  "userId": "{{UserId}}",
  "passwordToken": "{{PasswordToken}}",
  "newPassword": "NewPassword123!"
}

###

# GET Users GetCurrentUserInformation
GET {{Web_HostAddress}}/Users/GetCurrentUserInformation
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

###

# POST Reset Database
POST {{Web_HostAddress}}/WeatherForecasts/ResetDatabase
Content-Type: application/json

###

# GET WeatherForecast
GET {{Web_HostAddress}}/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###