# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001/api/v1

# Super Admin Credentials
# @Email=superadmin@connectflow.local
# @Password=SuperAdmin123!

# Tenant Admin Credentials
# @Email=tenantadmin@connectflow.local
# @Password=TenantAdmin123!

@Email=syed@test.com
@Password=SyedWaqas123!

@UserId=83fd0584-f166-4cf4-8e72-8651e37d9edd
@EmailConfirmationToken=CfDJ8I9Tjk8vOcdNsFAAFQwFrUC6R9oDZpEQsreqYxp20ZkFfnJVzt46X1HrlV5Vu5C5OZirylcDAIx3ThI1aWNVh3E3uVtTXxQ0QslL4NP/C6RUlm5Kf/JSxSy8Pmu+k7t3Ny2cZHU9Wf9N1tbiSGGCtJy7ImucV5HUjeK8uTEClU53dhJcb7H77e+S8I+hsdrZww==
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4M2ZkMDU4NC1mMTY2LTRjZjQtOGU3Mi04NjUxZTM3ZDllZGQiLCJqdGkiOiI3ZDUzYmYwZS04OGFjLTQ1OGQtYTBkZi01MDc1MGUwZGVhZTkiLCJpYXQiOjE3NTQ3MzE4MTgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiODNmZDA1ODQtZjE2Ni00Y2Y0LThlNzItODY1MWUzN2Q5ZWRkIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InN5ZWRAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzeWVkQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc2lkIjoiMTAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZW5hbnRBZG1pbiIsIm5iZiI6MTc1NDczMTgxOCwiZXhwIjoxNzU0NzM1NDE4LCJpc3MiOiJDb25uZWN0Rmxvdy5EZXYiLCJhdWQiOiJDb25uZWN0Rmxvdy5EZXYifQ.H_gPohHge8szaSS1H1AOR1mx_mS6R3wrBO7uvR-gA8I
@RefreshToken=2zBPfUGOS42c+bEIZJxhEW4v3OjR59xZ3KIPJ0AU+eB2ZYIXsU4Wt0tNZO13Hnp05APoP51++KSxPh1gLo8N+Q==

# POST Users Register
POST {{Web_HostAddress}}/Users/Register
Content-Type: application/json

{
  "email": "syed@test.com",
  "password": "SyedWaqas123!",
  "firstName": "Syed",
  "lastName": "Waqas"
}

###

# POST Users Login
POST {{Web_HostAddress}}/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users ConfirmEmail
POST {{Web_HostAddress}}/Users/ConfirmEmail
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "confirmationToken": "{{EmailConfirmationToken}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/Users/Refresh
Content-Type: application/json

{
  "accessToken": "{{BearerToken}}",
  "refreshToken": "{{RefreshToken}}"
}

###

# GET Users GetCurrentUserInformation
GET {{Web_HostAddress}}/Users/GetCurrentUserInformation
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

###

# GET WeatherForecast
GET {{Web_HostAddress}}/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###