# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001/api/v1

# Super Admin Credentials
# @Email=superadmin@connectflow.local
# @Password=SuperAdmin123!

# Tenant Admin Credentials
@Email=tenantadmin@connectflow.local
@Password=TenantAdmin123!

//@Email=syed@test.com
//@Password=SyedWaqas123!

@UserId=2b4b34b1-328e-4ad6-b672-83643da470c6
@EmailConfirmationToken=CfDJ8I9Tjk8vOcdNsFAAFQwFrUBPNKHY0BHG9ScrNVFiUXeph9J1FZF+umwlBxHYYZHkYLtIpjL0Xj12vyMh+fWVNzZ96hv882/61cEBBgnXrTRc66wBMi7MrqRZGjB5Lb1IOjikoISb2wGhytShb7rzKc1Imo06tH78KJZpwpruRMaSoq2FvG9qC34Y/bxQYz13Og==
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NGM1Y2IzNC1lYzRlLTQ0N2EtODJjYi0yODk2YWJiZTI0ZjgiLCJqdGkiOiJhNTQ1NzQ2OC0zNDE5LTQwYjktOWJjMC1jN2ZlNGMxMTI5YWIiLCJpYXQiOjE3NTQ2NjM5NDgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiODRjNWNiMzQtZWM0ZS00NDdhLTgyY2ItMjg5NmFiYmUyNGY4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlbmFudGFkbWluQGNvbm5lY3RmbG93LmxvY2FsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidGVuYW50YWRtaW5AY29ubmVjdGZsb3cubG9jYWwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI3MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlRlbmFudEFkbWluIiwibmJmIjoxNzU0NjYzOTQ4LCJleHAiOjE3NTQ2Njc1NDgsImlzcyI6IkNvbm5lY3RGbG93LkRldiIsImF1ZCI6IkNvbm5lY3RGbG93LkRldiJ9.ERzl4xvlyZe7H377mywm85ZcBHPIt17DZUYReezboyw
@RefreshToken=2zBPfUGOS42c+bEIZJxhEW4v3OjR59xZ3KIPJ0AU+eB2ZYIXsU4Wt0tNZO13Hnp05APoP51++KSxPh1gLo8N+Q==

# POST Users Register
POST {{Web_HostAddress}}/Users/Register
Content-Type: application/json

{
  "email": "syed@test.com",
  "password": "SyedWaqas123!",
  "firstName": "Syed",
  "lastName": "Waqas"
}

###

# POST Users Login
POST {{Web_HostAddress}}/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users ConfirmEmail
POST {{Web_HostAddress}}/Users/ConfirmEmail
Content-Type: application/json

{
  "userId": "{{UserId}}",
  "confirmationToken": "{{EmailConfirmationToken}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/Users/Refresh
Content-Type: application/json

{
  "accessToken": "{{BearerToken}}",
  "refreshToken": "{{RefreshToken}}"
}

###

# GET Users GetCurrentUserInformation
GET {{Web_HostAddress}}/Users/GetCurrentUserInformation
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

###

# GET WeatherForecast
GET {{Web_HostAddress}}/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###